import uuid, enum
from datetime import datetime, timezone
from sqlalchemy import *
from sqlalchemy.orm import DeclarativeBase, relationship, Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID, BYTEA, JSONB, ARRAY, CITEXT

def now(): return datetime.now(timezone.utc)
class Base(DeclarativeBase): pass
class Role(str,enum.Enum): software_developer='software_developer'; business_developer='business_developer'
class ConnStatus(str,enum.Enum): pending='pending'; accepted='accepted'; declined='declined'
class IdeaCategory(str,enum.Enum): find_problem='find_problem'; build_product='build_product'; design_brand='design_brand'; run_campaign='run_campaign'; other='other'
class User(Base):
    __tablename__='users'; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); email=Column(CITEXT,unique=True,nullable=False); password_hash=Column(Text,nullable=False); display_name=Column(String(80),nullable=False); first_name=Column(String(50),nullable=False); is_admin=Column(Boolean,default=False,nullable=False); is_active=Column(Boolean,default=True,nullable=False); created_at=Column(DateTime(timezone=True),default=now); last_login_at=Column(DateTime(timezone=True)); email_verified_at=Column(DateTime(timezone=True)); profile=relationship('Profile',back_populates='user',uselist=False,cascade='all, delete-orphan')
class Session(Base):
    __tablename__='sessions'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); user_id=Column(UUID(as_uuid=True),ForeignKey('users.id',ondelete='CASCADE'),index=True); token_hash=Column(BYTEA,unique=True,index=True); csrf_token=Column(BYTEA); expires_at=Column(DateTime(timezone=True),index=True); created_at=Column(DateTime(timezone=True),default=now); last_used_at=Column(DateTime(timezone=True),default=now)
class MagicLinkToken(Base):
    __tablename__='magic_link_tokens'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); user_id=Column(UUID(as_uuid=True),ForeignKey('users.id')); token_hash=Column(BYTEA,unique=True); expires_at=Column(DateTime(timezone=True)); used_at=Column(DateTime(timezone=True)); created_at=Column(DateTime(timezone=True),default=now)
class Course(Base): __tablename__='courses'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); name=Column(String(100),unique=True,nullable=False)
class Skill(Base): __tablename__='skills'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); name=Column(String(100),unique=True,nullable=False); category=Column(String(50))
class Interest(Base): __tablename__='interests'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); name=Column(String(100),unique=True,nullable=False)
profile_skills=Table('profile_skills',Base.metadata,Column('profile_id',UUID(as_uuid=True),ForeignKey('profiles.id',ondelete='CASCADE'),primary_key=True),Column('skill_id',UUID(as_uuid=True),ForeignKey('skills.id',ondelete='CASCADE'),primary_key=True),Column('created_at',DateTime(timezone=True),default=now))
profile_interests=Table('profile_interests',Base.metadata,Column('profile_id',UUID(as_uuid=True),ForeignKey('profiles.id',ondelete='CASCADE'),primary_key=True),Column('interest_id',UUID(as_uuid=True),ForeignKey('interests.id',ondelete='CASCADE'),primary_key=True),Column('created_at',DateTime(timezone=True),default=now))
class Photo(Base): __tablename__='photos'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); user_id=Column(UUID(as_uuid=True),ForeignKey('users.id',ondelete='CASCADE')); content_type=Column(String(50)); byte_size=Column(Integer); data=Column(BYTEA); created_at=Column(DateTime(timezone=True),default=now)
class Profile(Base):
    __tablename__='profiles'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); user_id=Column(UUID(as_uuid=True),ForeignKey('users.id',ondelete='CASCADE'),unique=True); bio=Column(String(500)); role=Column(Enum(Role,name='user_role')); course_id=Column(UUID(as_uuid=True),ForeignKey('courses.id')); looking_for=Column(String(300)); photo_id=Column(UUID(as_uuid=True),ForeignKey('photos.id')); profile_complete=Column(Boolean,default=False); created_at=Column(DateTime(timezone=True),default=now); updated_at=Column(DateTime(timezone=True),default=now,onupdate=now); user=relationship('User',back_populates='profile'); course=relationship('Course'); skills=relationship('Skill',secondary=profile_skills,lazy='selectin'); interests=relationship('Interest',secondary=profile_interests,lazy='selectin'); photo=relationship('Photo',foreign_keys=[photo_id])
class ConnectionRequest(Base):
    __tablename__='connection_requests'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); sender_id=Column(UUID(as_uuid=True),ForeignKey('users.id')); receiver_id=Column(UUID(as_uuid=True),ForeignKey('users.id')); status=Column(Enum(ConnStatus,name='connection_status'),default=ConnStatus.pending); message=Column(String(300)); created_at=Column(DateTime(timezone=True),default=now); responded_at=Column(DateTime(timezone=True)); responded_by=Column(UUID(as_uuid=True),ForeignKey('users.id')); __table_args__=(CheckConstraint('sender_id <> receiver_id'),Index('one_request_per_pair',func.least(sender_id,receiver_id),func.greatest(sender_id,receiver_id),unique=True),)
class Thread(Base): __tablename__='threads'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); connection_request_id=Column(UUID(as_uuid=True),ForeignKey('connection_requests.id'),unique=True); created_at=Column(DateTime(timezone=True),default=now)
class Message(Base): __tablename__='messages'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); thread_id=Column(UUID(as_uuid=True),ForeignKey('threads.id',ondelete='CASCADE'),index=True); sender_id=Column(UUID(as_uuid=True),ForeignKey('users.id')); body=Column(Text); created_at=Column(DateTime(timezone=True),default=now,index=True)
class ReadReceipt(Base): __tablename__='read_receipts'; thread_id=Column(UUID(as_uuid=True),ForeignKey('threads.id'),primary_key=True); user_id=Column(UUID(as_uuid=True),ForeignKey('users.id'),primary_key=True); last_read_at=Column(DateTime(timezone=True),default=now)
class Notification(Base): __tablename__='notifications'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); user_id=Column(UUID(as_uuid=True),ForeignKey('users.id',ondelete='CASCADE'),index=True); type=Column(String(40)); actor_id=Column(UUID(as_uuid=True),ForeignKey('users.id')); connection_request_id=Column(UUID(as_uuid=True),ForeignKey('connection_requests.id')); thread_id=Column(UUID(as_uuid=True),ForeignKey('threads.id')); project_idea_id=Column(UUID(as_uuid=True)); data=Column(JSONB,default=dict); read_at=Column(DateTime(timezone=True)); created_at=Column(DateTime(timezone=True),default=now,index=True)
class ProjectIdea(Base): __tablename__='project_ideas'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); author_id=Column(UUID(as_uuid=True),ForeignKey('users.id',ondelete='CASCADE'),index=True); title=Column(String(120)); description=Column(Text); category=Column(Enum(IdeaCategory,name='idea_category')); skills_needed=Column(ARRAY(String)); course_id=Column(UUID(as_uuid=True),ForeignKey('courses.id')); is_open=Column(Boolean,default=True); created_at=Column(DateTime(timezone=True),default=now); updated_at=Column(DateTime(timezone=True),default=now,onupdate=now)
class IdeaInterest(Base): __tablename__='idea_interests'; idea_id=Column(UUID(as_uuid=True),ForeignKey('project_ideas.id',ondelete='CASCADE'),primary_key=True); user_id=Column(UUID(as_uuid=True),ForeignKey('users.id'),primary_key=True); created_at=Column(DateTime(timezone=True),default=now)
class AdminAuditLog(Base): __tablename__='admin_audit_log'; id=Column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); admin_id=Column(UUID(as_uuid=True),ForeignKey('users.id')); action=Column(String(50)); target_type=Column(String(50)); target_id=Column(UUID(as_uuid=True)); metadata_json=Column('metadata',JSONB,default=dict); created_at=Column(DateTime(timezone=True),default=now,index=True)
